### ISSUE TITLE
[LookUpAnything] Island Fridge is ignored

### ISSUE THREAD

**Issue by MithranArkanere** [Pathoschild/LookupAnything#606] opened 2021-01-27 19:07 UTC
Items stored in the Island Farmhouse's fridge are ignored by the mod, so they will not be added to the Owned counter.

**Comment by dewiniaid** [comment] 2021-01-27 22:08
I've also seen all the island chests ignored, including hitting F1 on a Dragon Tooth showing I have 0 of them while looking in a chest that had 9.

**Comment by Pathoschild** [comment] 2021-01-28 00:13
@MithranArkanere Fixed in the upcoming Lookup Anything 1.32.4. Thanks for reporting it!

@dewiniaid I can't reproduce that:
> ![image](https://user-images.githubusercontent.com/230581/106071074-a1920780-60d3-11eb-9cbf-f629aae3fe72.png)
> ![image](https://user-images.githubusercontent.com/230581/106071083-aa82d900-60d3-11eb-9445-f6fb4a08a9f3.png)
Does that happen with chests in a specific island location?

**Comment by dewiniaid** [comment] 2021-01-28 22:09
It was on the Island farm.  There's other times I've had it misreport item counts as well though -- possibly related to being the second player and not the host of the game.

**Comment by Pathoschild** [comment] 2021-01-29 00:46
Oh, that's normal then. As a farmhand you don't have access to the whole world, only a limited number of synced locations (including the main farm and your current location). so in that case it'll only count the items that exist in the parts of the world that currently exist in your game.

**Closed as completed** 2021-01-29 00:52 UTC
Labels: not a dev task
