### ISSUE TITLE
Incorrect villager information displayed on social page

### ISSUE THREAD

**Issue by vizv** [Pathoschild/LookupAnything#25] opened 2016-11-20 19:35 UTC
After married to Emily, on social page, scroll down, and lookup anyone on the first row after scroll it displayed information about Emily.

For example, after scrolling, when inspect "Linus" it displays "Emily" instead, other villagers than the first row displays correctly.
 
<img width="1080" alt="screenshot_20161120_152633" src="https://cloud.githubusercontent.com/assets/1577163/20465582/8c731f72-af36-11e6-8683-ba034e2418e3.png">

**Comment by Pathoschild** [comment] 2016-11-20 20:04
Confirmed; I'll look into it for the upcoming 1.8 release. :)

**Comment by Pathoschild** [comment] 2016-11-20 22:50
Fixed in the upcoming 1.8 release.

**Closed by Pathoschild** 2016-11-20 22:50 UTC
Labels: bug

**Comment by rikai** [comment] 2022-01-27 18:55
This issue appears to have cropped up again with modded NPCs.

I am currently seeing this with [Lunna](https://www.nexusmods.com/stardewvalley/mods/6626) and [Richard](https://www.nexusmods.com/stardewvalley/mods/7286) among others.

**Comment by Pathoschild** [comment] 2024-06-06 02:46
@rikai Does that still happen with the latest versions? If so, I suggest filing a new bug report (since comments on a closed bug report are easy to miss).
