### ISSUE TITLE
[Lookup Anything] Only show likes/dislikes once given to villager

### ISSUE THREAD

**Issue by ejektaflex** [Pathoschild/LookupAnything#371] opened 2019-02-03 10:49 UTC
It would be nice if, as a config option, you only saw the loves/likes/neutral/dislikes of a villager for items which you had already given to them. Many people do still like the vanilla Stardew mechanic where you won't know whether or not a villager will like a certain gift until it is given - so this would allow them to still use your mod without spoiling themselves the ability to learn which foods a villager likes and doesn't like on their own.

Plus, when using mods like Artisan Valley, these fields get *very* long (The "likes" field is 132 lines long, for example). Limiting this field to only show given items would very much reduce the amount of clutter used when a lot of content exists.

**Comment by Pathoschild** [comment] 2019-02-03 17:54
Thanks for the suggestion! That's something I've wanted to do for a while, but I haven't gotten to it since I mostly work on SMAPI and helping maintain mods currently. I'll close this one as a duplicate of #6 though.

**Closed as completed by Pathoschild** 2019-02-03 17:54 UTC
Labels: duplicate

**Comment by ejektaflex** [comment] 2019-02-04 04:16
Ah, never got to look that far back in the issue tracker. Hopefully it gets added!
