### ISSUE TITLE
[Content Patcher] OOM Exceptions from Content Patcher

### ISSUE THREAD

**Issue by minervamaga** [Pathoschild/LookupAnything#589] opened 2021-01-03 22:36 UTC
I am still experiencing OOM exception failures after the 1.5 update.  I have removed multiple memory heavy mods trying to relieve the issue, without much success.  It appears to be Content Patcher failing pretty consistently, and on the `Cursors` edits at that.  I am aware of other players with far more mods than me at this point who are not experiencing this same issue, so frankly I'm baffled.  My team also has multiple complaints reported to us of lag with the time based tokens, similar to the issues players experienced when the location tokens were introduced.

Log with performance stats and OOM exceptions: https://smapi.io/log/da51fb135bc4422d97ec3f520e3091b7

**Comment by Pathoschild** [comment] 2021-01-04 03:52
Hi! I've seen more reported `OutOfMemoryException` errors after the 1.5 update, so I'm tracking reports in Pathoschild/SMAPI#749. I'm not sure whether it's an issue with Content Patcher itself; it loads a lot of content, so it's also more likely to fail first if there are memory issues.

The best case would be if I could reproduce it myself; then I could run some tests and profiling. I could see if I get the same errors with your `Mods` folder if you want to send me a link over Discord.

I'll close this ticket since I'm already tracking it under Pathoschild/SMAPI#749, but feel free to comment there or message me on Discord if you have any other info.

**Closed as completed by Pathoschild** 2021-01-04 03:52 UTC
Labels: duplicate
