### ISSUE TITLE
[Lookup Anything] Using the mod breaks the villager tab

### ISSUE THREAD

**Issue by Tminus1** [Pathoschild/LookupAnything#327] opened 2018-09-17 13:59 UTC
As soon as I press F1, the villager tab breaks and stays like that till I restart the game.

![2018-09-17_16-32-06](https://user-images.githubusercontent.com/40320559/45627407-8e4de680-ba9a-11e8-904c-902483ae4835.jpg)

I tried disabling my other mods and it still happened.

Some more info:
- I *can* scroll, even if the scroll bar is not visible
- the empty space at the bottom stays empty even when I scroll down

**Comment by Pathoschild** [comment] 2018-09-17 17:10
Can you try again with no other mods installed, then post a new screenshot and [link to your SMAPI log](https://log.smapi.io/)?

**Comment by Tminus1** [comment] 2018-09-17 17:38
https://log.smapi.io/c0817034

I didn't remove Console Commands and Save Backup since those are default with SMAPI.

**Comment by Pathoschild** [comment] 2018-09-17 22:45
Can you post the new screenshot too?

**Comment by Tminus1** [comment] 2018-09-18 08:04
Well, it looks the same, but without the mods stuff, but there you go: [screenshot](https://i.imgur.com/NJaytCH.jpg) and a [gif of me scrolling](https://i.imgur.com/4JsIbLU.gifv).

**Comment by Pathoschild** [comment] 2018-11-09 01:55
Tentatively fixed in the upcoming Lookup Anything 1.20. I can't reproduce this to confirm though, so let me know if it still happens once you have that version!

**Closed as completed by Pathoschild** 2018-11-09 01:55 UTC
Labels: bug
