### ISSUE TITLE
[Content Patcher] Special order board won't show

### ISSUE THREAD

**Issue by Warilized** [Pathoschild/LookupAnything#590] opened 2021-01-04 09:15 UTC
Using "Load" action reverts the SO board to nothing.

It still had the ! New Quest icon, amusingly.

**Comment by Pathoschild** [comment] 2021-01-04 17:52
@Warilized Can you attach a zip of the content pack with that issue?

**Comment by Pathoschild** [comment] 2021-01-10 22:19
I'll close this ticket since I don't have the content pack to reproduce it, but it's probably caused by Pathoschild/SMAPI#751.

**Closed as completed by Pathoschild** 2021-01-10 22:19 UTC
Labels: not a dev task
